"""
API Client for Ozone Recon REST API

This module handles HTTP requests to the Recon API endpoints based on tool calls
generated by the Gemini client.
"""

import requests
from typing import Dict, Any, Optional
from urllib.parse import urljoin, urlencode


class ReconApiClient:
    def __init__(self, base_url: str = "http://localhost:9888", timeout: int = 30):
        """
        Initialize the Recon API client.
        
        Args:
            base_url: Base URL of the Recon service (default: http://localhost:9888)
            timeout: Request timeout in seconds
        """
        self.base_url = base_url.rstrip('/')
        self.timeout = timeout
        self.session = requests.Session()
        
        # Set default headers
        self.session.headers.update({
            'Accept': 'application/json',
            'User-Agent': 'Ozone-Recon-Chatbot/1.0'
        })
    
    def execute_tool_call(self, tool_call: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute a tool call by making an HTTP request to the specified endpoint.
        
        Args:
            tool_call: Dictionary containing endpoint, method, and parameters
            
        Returns:
            Dictionary containing the API response data
            
        Raises:
            Exception: If the API request fails
        """
        endpoint = tool_call.get('endpoint', '')
        method = tool_call.get('method', 'GET').upper()
        parameters = tool_call.get('parameters', {})
        
        # Construct the full URL
        if not endpoint.startswith('/api/v1/'):
            endpoint = '/api/v1' + endpoint if endpoint.startswith('/') else '/api/v1/' + endpoint
            
        url = self.base_url + endpoint
        
        try:
            if method == 'GET':
                # Handle path parameters (replace {param} in URL)
                for param_name, param_value in parameters.items():
                    if f'{{{param_name}}}' in url:
                        url = url.replace(f'{{{param_name}}}', str(param_value))
                        parameters.pop(param_name, None)
                
                # Add remaining parameters as query parameters
                if parameters:
                    url += '?' + urlencode(parameters)
                
                response = self.session.get(url, timeout=self.timeout)
                
            elif method == 'POST':
                response = self.session.post(url, json=parameters, timeout=self.timeout)
                
            elif method == 'PUT':
                response = self.session.put(url, json=parameters, timeout=self.timeout)
                
            else:
                raise ValueError(f"Unsupported HTTP method: {method}")
            
            # Check if the request was successful
            response.raise_for_status()
            
            # Try to parse JSON response
            try:
                return response.json()
            except ValueError:
                # If response is not JSON, return the text content
                return {"response": response.text, "status_code": response.status_code}
                
        except requests.exceptions.ConnectionError:
            raise Exception(f"Could not connect to Recon service at {self.base_url}. Please ensure Recon is running.")
        
        except requests.exceptions.Timeout:
            raise Exception(f"Request to {url} timed out after {self.timeout} seconds.")
        
        except requests.exceptions.HTTPError as e:
            if response.status_code == 404:
                raise Exception(f"API endpoint not found: {endpoint}")
            elif response.status_code == 500:
                raise Exception(f"Internal server error from Recon API: {e}")
            else:
                raise Exception(f"HTTP error {response.status_code}: {e}")
        
        except Exception as e:
            raise Exception(f"Unexpected error calling Recon API: {e}")
    
    def test_connection(self) -> bool:
        """
        Test if the Recon service is accessible.
        
        Returns:
            True if connection is successful, False otherwise
        """
        try:
            response = self.session.get(f"{self.base_url}/api/v1/clusterState", timeout=5)
            return response.status_code == 200
        except:
            return False
    
    def get_service_info(self) -> Dict[str, Any]:
        """
        Get basic information about the Recon service.
        
        Returns:
            Dictionary with service information
        """
        try:
            cluster_state = self.execute_tool_call({
                "endpoint": "/clusterState",
                "method": "GET",
                "parameters": {}
            })
            
            return {
                "status": "connected",
                "base_url": self.base_url,
                "cluster_info": {
                    "total_datanodes": cluster_state.get("totalDatanodes", "unknown"),
                    "healthy_datanodes": cluster_state.get("healthyDatanodes", "unknown"),
                    "pipelines": cluster_state.get("pipelines", "unknown"),
                    "containers": cluster_state.get("containers", "unknown")
                }
            }
        except Exception as e:
            return {
                "status": "error",
                "base_url": self.base_url,
                "error": str(e)
            }


